# Generated by Django 3.2.7 on 2022-01-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_feedback_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports', models.URLField(verbose_name='https://admin.uniongates.com/Report.html')),
            ],
        ),
    ]
