# Generated by Django 3.2.7 on 2022-01-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_product',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
