# Generated by Django 3.2.7 on 2022-01-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_products_is_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
